# Usar una imagen oficial de Nginx como servidor web
FROM nginx:stable-alpine

# Copiar los archivos estáticos (HTML, CSS, JS) al directorio público de Nginx
COPY . /usr/share/nginx/html

# Exponer el puerto 80
EXPOSE 80